apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app-dev
  labels:
    name: spring-boot-app-dev
    environment: dev
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted